server:
  port: 8084

spring:
  application:
    name: business-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    dynamic:
      primary: fescar
      strict: true
      seata: true    #开启seata代理，开启后默认每个数据源都代理，如果某个不需要代理可单独关闭
      seata-mode: AT #支持XA及AT模式,默认AT
      datasource:
        fescar:
          username: root
          password: root
          url: jdbc:mysql://localhost:3306/fescar?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

seata:
  enabled: true
  application-id: business-service
  tx-service-group: my_test_tx_group
  #一定要是false
  enable-auto-data-source-proxy: false
  service:
    vgroup-mapping:
      #key与上面的tx-service-group的值对应
      my_test_tx_group: default
    grouplist:
      #seata-server地址仅file注册中心需要
      default: localhost:8091
  config:
    type: file
  registry:
    type: file
